filegroup(
    name = "candidate_window_logo",
    srcs = [
        "candidate_window_logo_PBGRA32_100.bmp",
        "candidate_window_logo_PBGRA32_125.bmp",
        "candidate_window_logo_PBGRA32_150.bmp",
        "candidate_window_logo_PBGRA32_200.bmp",
    ],
    visibility = ["//:__subpackages__"],
)
