name: CI for Linux
# https://github.com/google/mozc/blob/master/docs/build_mozc_in_docker.md

# Run on push.
on: push

permissions: read-all

# Prevent previous workflows from running.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    container:
      image: "debian:12.1"

    steps:
      - name: Setup
        run: |
          apt-get update
          apt-get install -y git build-essential libibus-1.0-dev qtbase5-dev
          #
          # Unset the Android NDK setting to skip the unnecessary configuration.
          echo "ANDROID_NDK_HOME=" >> $GITHUB_ENV
          # Install Bazel
          apt-get install -y curl gnupg libncurses5
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
          apt-get update
          apt-get install -y bazel

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: bazel build
        working-directory: ./src
        run: |
          bazel build --config oss_linux package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mozc.zip
          path: src/bazel-bin/unix/mozc.zip
          if-no-files-found: warn
