name: CI for macOS
# https://github.com/google/mozc/blob/master/docs/build_mozc_in_osx.md

# Run on push.
on: push

permissions: read-all

# Prevent previous workflows from running.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md
    runs-on: macos-15
    timeout-minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Try to restore update_deps cache
        uses: actions/cache@v4
        with:
          path: src/third_party_cache
          key: update_deps-${{ runner.os }}-${{ hashFiles('src/build_tools/update_deps.py') }}

      - name: Install dependencies
        working-directory: ./src
        # This command uses src/third_party_cache as the download cache.
        run: |
          python3 build_tools/update_deps.py

      - name: bazel test
        working-directory: ./src
        run: |
          bazelisk test //mac:mozc_imk_input_controller_test  --config oss_macos --build_tests_only -c dbg --test_arg=--stderrthreshold=0 --test_output=all --cache_test_results=no

      - name: bazel test (again)
        working-directory: ./src
        run: |
          bazelisk test //mac:mozc_imk_input_controller_test  --config oss_macos --build_tests_only -c dbg --test_arg=--stderrthreshold=0 --test_output=all --cache_test_results=no

      - name: bazel test (again2)
        working-directory: ./src
        run: |
          bazelisk test //mac:mozc_imk_input_controller_test  --config oss_macos --build_tests_only -c dbg --test_arg=--stderrthreshold=0 --test_output=all --cache_test_results=no

      - name: bazel test (again3)
        working-directory: ./src
        run: |
          bazelisk test //mac:mozc_imk_input_controller_test  --config oss_macos --build_tests_only -c dbg --test_arg=--stderrthreshold=0 --test_output=all --cache_test_results=no
